name: Immoturkije
favicon: null
layout_spectrum: 0.72855
typography_spectrum: 0.58509
title: Uw vastgoedpartner in de regio Side / Turkije.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#799dd1'
    - '#bbbbdd'
    - '#1c1d0d'
    - '#616b6c'
    - '#3e433d'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
