name: Immoturkije
favicon: null
layout_spectrum: 0.92976
typography_spectrum: 0.15705
title: Uw vastgoedpartner in de regio Side / Turkije.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#002955'
    - '#178adb'
    - '#86cfd6'
    - '#929970'
    - '#eee7bb'
  brandStrength: 0.375
  lightness: 0.6875
  saturation: 0.6992555989418179
  rhythmicContrast: 0.60822843038477
purpose: []
