typography_spectrum: 0.58509
color:
  brandColors:
    - '#799dd1'
    - '#bbbbdd'
    - '#1c1d0d'
    - '#616b6c'
    - '#3e433d'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.50037
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/66cf317b-d8ed-47e3-b5cf-b92772945d30.jpg
name: Immoturkije
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Appartementen TE KOOP
    id: 1d1e55f7-16d1-4263-851a-8c02ac48e5e3
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/aeedfb60-5e22-4c92-8bc1-994866fb6ee5.ico
title: Uw vastgoedpartner in de regio Side / Turkije.
purpose: []
