name: Immoturkije
favicon: null
layout_spectrum: 1
typography_spectrum: 0.85802
title: Uw vastgoedpartner in de regio Side / Turkije.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ea8a12'
    - '#734f1d'
    - '#ac671f'
    - '#40301b'
  brandStrength: 0.75
  lightness: 0.875
  saturation: 0.125
  rhythmicContrast: 0.60822843038477
purpose: []
